#!/bin/bash


# Removes the carriage return inserted by windows
remove_carriage (){
	echo `echo $1 | sed 's/\r//g'`
}
	

passenger_name=`zenity --entry --title="Traveler Name" --text="What is the traveler's name?"`	#Prompts user to enter a name.  Can play with options

#Removes carriage returns
passenger_name=`remove_carriage $test`


departure_date=`zenity --calendar --text="What is the departure date?"`

echo $departure_date

return_date=`zenity --calendar --text="What is the return date?"`

echo $return_date

echo $departure_date | cat > dates
# use sed -n "/^$variable/p" to find out of an entry exists for that person. If so, use grep -v $variable > to write new file without that entry, then echo $variable >> reservations.txt to append the new scheduled trip.


# new idea: grep -v ^$variable reservations.txt temp.txt
# then copy temp.txt into reservations.txt to remove the reservation already under person's name.
# To append, use echo $reservation_info >> reservation.txt



#presence=`grep ^$test bullshit.txt`
#echo $presence

#if [[ $presence != '' ]]
#then
#	echo grep -v ^$test bullshit.txt
#else
#	echo "cheese balls"
#fi	
